package hibernate.entidades;
// Generated 23 feb 2026, 14:18:32 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ThDepartamento generated by hbm2java
 */
public class ThDepartamento implements java.io.Serializable {

	private byte deptNo;
	private String dnombre;
	private String loc;
	private Set thEmpleados = new HashSet(0);

	public ThDepartamento() {
	}

	public ThDepartamento(byte deptNo, String dnombre, String loc) {
		this.deptNo = deptNo;
		this.dnombre = dnombre;
		this.loc = loc;
	}

	public ThDepartamento(byte deptNo, String dnombre, String loc, Set thEmpleados) {
		this.deptNo = deptNo;
		this.dnombre = dnombre;
		this.loc = loc;
		this.thEmpleados = thEmpleados;
	}

	public byte getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(byte deptNo) {
		this.deptNo = deptNo;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	public Set getThEmpleados() {
		return this.thEmpleados;
	}

	public void setThEmpleados(Set thEmpleados) {
		this.thEmpleados = thEmpleados;
	}

}
