package hibernate.entidades;
// Generated 23 feb 2026, 14:18:32 by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ThEmpleado generated by hbm2java
 */
public class ThEmpleado implements java.io.Serializable {

	private short empNo;
	private ThDepartamento thDepartamento;
	private String apellido;
	private String oficio;
	private short dir;
	private Date fechaAlt;
	private BigDecimal salario;
	private BigDecimal comision;

	public ThEmpleado() {
	}

	public ThEmpleado(short empNo, ThDepartamento thDepartamento, String apellido, String oficio, short dir,
			Date fechaAlt, BigDecimal salario, BigDecimal comision) {
		this.empNo = empNo;
		this.thDepartamento = thDepartamento;
		this.apellido = apellido;
		this.oficio = oficio;
		this.dir = dir;
		this.fechaAlt = fechaAlt;
		this.salario = salario;
		this.comision = comision;
	}

	public short getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(short empNo) {
		this.empNo = empNo;
	}

	public ThDepartamento getThDepartamento() {
		return this.thDepartamento;
	}

	public void setThDepartamento(ThDepartamento thDepartamento) {
		this.thDepartamento = thDepartamento;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public short getDir() {
		return this.dir;
	}

	public void setDir(short dir) {
		this.dir = dir;
	}

	public Date getFechaAlt() {
		return this.fechaAlt;
	}

	public void setFechaAlt(Date fechaAlt) {
		this.fechaAlt = fechaAlt;
	}

	public BigDecimal getSalario() {
		return this.salario;
	}

	public void setSalario(BigDecimal salario) {
		this.salario = salario;
	}

	public BigDecimal getComision() {
		return this.comision;
	}

	public void setComision(BigDecimal comision) {
		this.comision = comision;
	}

}
